server:
  port: 8085
spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9097
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: user-search-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.nexo.userservice.dto.UserSearchEvent
      auto-offset-reset: earliest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/nexo-network
          jwk-set-uri: http://localhost:9090/realms/nexo-network/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: 9092
  client:
    upload-file-service:
      address: "static://localhost:9093"
      negotiationType: plaintext
    messaging-service:
      address: "static://localhost:9095"
      negotiationType: plaintext

logging:
  level:
    org.nexo.userservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

meilisearch:
  host: http://localhost:7700
  apiKey: masterKey
  index:
    users: users

kafka:
  topics:
    user-events: user-events
