server:
  port: 8086
spring:
  application:
    name: files
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
grpc:
  client:
    posts:
      address: static://localhost:9091
      negotiationType: plaintext
app:
  firebase:
    file: serviceAccountKey.json
    bucket: savefileimage.appspot.com