server:
  port: 8081

spring:
  application:
    name: auth
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
keycloak:
  serverUrl: http://localhost:9090
  realm: nexo-network
  clientId: auth-service-client
  adminUsername: admin
  adminPassword: admin

logging:
  level:
    org.nexo.authservice: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG

grpc:
  client:
    user-service:
      address: "static://localhost:9092"
      negotiationType: plaintext
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
