server:
  port: 8081

spring:
  application:
    name: auth
  main:
    allow-bean-definition-overriding: true
  webflux:
    base-path: /
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
keycloak:
  serverUrl: ${KEYCLOAK_SERVERURL:http://localhost:9090}
  realm: nexo-network
  clientId: auth-service-client
  adminUsername: admin
  adminPassword: admin

logging:
  level:
    org.nexo.authservice: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG
    io.netty: INFO

grpc:
  server:
    port: 9099
  client:
    user-service:
      address: ${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://localhost:9092}
      negotiationType: plaintext
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
