server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      port: 6379
      host: localhost
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            websocket:
              max-frame-payload-length: 65536
          globalcors:
            cors-configurations:
              "[/api/**]":
                allowedOriginPatterns:
                  - "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true

          routes:
            - id: user-service
              uri: lb://users
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: lb://posts
              predicates:
                - Path=/api/posts/**
              filters:
                - StripPrefix=2

            - id: feed-service
              uri: lb://feeds
              predicates:
                - Path=/api/feeds/**
              filters:
                - StripPrefix=2
            #                - name: RequestRateLimiter
            #                  args:
            #                    redis-rate-limiter.replenishRate: 20
            #                    redis-rate-limiter.burstCapacity: 20
            #                    redis-rate-limiter.key-resolver: "#{@userKeyResolver}"

            - id: auth-service
              uri: lb://auth
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

            - id: interaction-service
              uri: lb://interaction
              predicates:
                - Path=/api/interaction/**
              filters:
                - StripPrefix=2

            - id: notification-service
              uri: lb://notifications
              predicates:
                - Path=/api/notifications/**
              filters:
                - StripPrefix=2
            - id: notification-websocket-route
              uri: lb://notifications
              predicates:
                - Path=/ws/**
              metadata:
                websocket: true

            - id: messaging-service-ws
              uri: lb:ws://messaging
              predicates:
                - Path=/messaging/ws/**
              filters:
                - StripPrefix=1

            - id: messaging-service
              uri: lb://messaging
              predicates:
                - Path=/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
